FORMAT: 1A
host: https://arato-api.herokuapp.com
# arato
Notes API is a *short texts saving* service similar to its physical paper presence on your table.




# Group Authentication
Notes related resources of the **Authentication API**








# Group alerts
Notes related resources of the **Alerts API**








## Alerts Collection [/api/v1/alerts{?page,limit,userId,sort,order}]
### List all Alerts [GET]
+ Parameters
    + page (optional, number) ... The page
    + userId (optional, string) ... A user id to filter from
    + limit = `20` (optional, number) ... The number of elements per page. Maximum `50`.
    + sort  = `id` (optional, string) ... The field to sort from.
        + Values
            + `id`
            + `created_at`
            + `price`
    + order = `desc`(optional, string) ... The order of sorting.
        + Values
            + `asc`
            + `desc`




+ Response 200 (application/json)




        {
            "users":[{
                    "id":1,
                    "email":"email@example.com",
                    "sequence_number":0
                }
            ],
            "paginate":{
                "total_count":1,
                "total_pages":1,
                "current_page":1,
                "limit":20
            }
        }




+ Response 401




### Create an Alert [POST]
+ Request (application/json)




        {
            "title": "My title",
            "price" : "10",
            "content" : "Hello"
        }




+ Response 201 (application/json)




        { "id": 3, "title": "Buy cheese and bread for breakfast." }




# Group Users
Notes related resources of the **Users API**








## Users Collection [/api/v1/users{?since}]
### List all Users [GET]
+ Parameters
    + since (optional, string) ... dfdfdfd dfsdf df sdf
+ Response 200 (application/json)




        {
            "users":[{
                    "id":1,
                    "email":"email@example.com",
                    "sequence_number":0
                }
            ],
            "paginate":{
                "total_count":1,
                "total_pages":1,
                "current_page":1,
                "limit":20
            }
        }




+ Response 403




### Create a User [POST]
+ Request (application/json)




        {
            "email": "email@example.com",
            "password" : "password",
            "password_confirmation" : "password"
        }




+ Response 201 (application/json)




        { "id": 3, "title": "Buy cheese and bread for breakfast." }




## Note [/notes/{id}]
A single Note object with all its details




+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.




### Retrieve a Note [GET]
+ Response 200 (application/json)




    + Header




            X-My-Header: The Value




    + Body




            { "id": 2, "title": "Pick-up posters from post-office" }




### Remove a Note [DELETE]
+ Response 204
